# ----------------------------
# docker-compose.yml para n8n Enterprise Hack
# ----------------------------
version: '3.8'

services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n"]
      interval: 5s
      timeout: 5s
      retries: 5

  n8n:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Conexão com Postgres
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: db
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n

      # Timezone e migrações
      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_DATABASE_MIGRATE: 'true'

      # Basic Auth
      N8N_BASIC_AUTH_ACTIVE: 'true'
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: secret

      # Hack Enterprise
      N8N_SKIP_LICENSE_CHECK: 'true'

      # Porta interna
      N8N_PORT: '5678'

    ports:
      - '5678:5678'
    volumes:
      - ./data/n8n:/home/node/.n8n

